version: '2'

services:
  web:
    container_name: angularjs4_web
    
    build:
      context: ./
      dockerfile: Dockerfile
    image: nginx
    ports:
      - 8080:80
      - 443:443
    #network_mode: "bridge"
    #expose:
    #  - 8080
    #networks:
    #  - code-network

    #volumes:
    #  - $pwd/angular4_jwt_webroot:/usr/share/nginx/html
    #  - ./site.conf:/etc/nginx/conf.d/default.conf
    #extra_hosts:
    #  - "oauth_server:172.22.201.35"

#networks:
#  code-network:
#    driver: bridge
#networks:
#  default:
#    external:
#      name: bridge